ALTER TABLE public.resumes
  ADD COLUMN IF NOT EXISTS phone text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS location text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS linkedin text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS github text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS portfolio text NOT NULL DEFAULT '';